chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from chat.views import index
from django.urls import path

urlpatterns = [
    path('', index),
    url(r'^(?P<open_chat>\w+)/?$', index),
]

faunamira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from faunamira import settings
from django.contrib.auth import views as auth_views
from blocks import user

urlpatterns = [
    # админка
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),

    # авторизация
    url(r'^accounts/', include('allauth.urls')),

    # редактор текста
    url(r'^tinymce/', include('tinymce.urls')),

    # страницы
    url(r'^', include('pages.home.urls')),
    url(r'^profile/', include('pages.userprofile.urls')),
    url(r'^animal/', include('pages.animal.urls')),
    url(r'^blog/', include('pages.blog.urls')),
    url(r'^dialogs/', include('pages.messager.urls')),

    # блоки
    url(r'^user_login/$', user.user_login, name='user_login'),
    url(r'^user_signup/$', user.user_signup, name='user_signup'),

    #chat
    url(r'^chat/', include('chat.urls')),

    #password reset
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/blog/urls.py
from django.conf.urls import url
from pages.blog.views import getBlogsView,BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogListAllView

urlpatterns = [
    # админка
    url(r'^list/(?P<username>.+)/$', BlogListView.as_view(), name='blog_list'), # (?P<username>.+)
    url(r'^detail/(?P<pk>[0-9]+)/$', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^create/$', BlogCreateView.as_view(), name='blog_create'),
    url(r'^update/(?P<pk>[0-9]+)/$', BlogUpdateView.as_view(), name='blog_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', BlogDeleteView.as_view(), name='blog_delete'),
    url(r'^$', BlogListAllView.as_view(), name='blog_all'),
    url(r'^getBlogs/(?P<blog_user>.+)/$', getBlogsView, name='getBlogs'),
    url(r'^getBlogs/$', getBlogsView, name='getBlogs'),
]

pages/blog/models.py
from django.db import models
from tinymce import models as tinymce_models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from dry_library.backend.thumbnails import CreateThumbnail
from pages.animal.models import Animal

class Blog(CreateThumbnail, models.Model):
    """
    Блог
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog', verbose_name=_('Author'))
    title = models.CharField(max_length=100, blank=False, null=False, verbose_name=_('Title'))
    article = tinymce_models.HTMLField(blank=False, null=False, verbose_name=_('Content'))
    date = models.DateTimeField(blank=False, null=False, verbose_name=_('Date of publication'))
    image = models.ImageField(max_length=100, upload_to='article', blank=True, null=True,verbose_name=_('Image'))
    image_thumb = models.ImageField(max_length=100, upload_to='article/thumbnail', blank=True, null=True)
    viewed = models.PositiveIntegerField(default=0, verbose_name=_('Viewed'))
    animals = models.ManyToManyField(Animal, blank=True)
    
    class Meta:
        ordering = ['-date']
        verbose_name = _('Blog')
        verbose_name_plural = _('Blog')

    def __str__(self):
         return (self.user.username) + ' ' + self.title

    def get_actual_articles(articles):
        act_articles = articles.filter(date__lte=timezone.now())
        return act_articles


    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = Blog.objects.get(pk=self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
                this_record.image_thumb.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=260, height=190, from_img=self.image, to_img=self.image_thumb)

        force_update = False

        if self.id:
            force_update = True

        super(Blog, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.image.delete(save=False)
        self.image_thumb.delete(save=False)
        super(Blog, self).delete(*args, **kwargs)


class BlogViewed(models.Model):
    """
    Модель для учета уникальных просмотров блога
    """
    blog_page = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_viewed', blank=False,
                                     verbose_name=_('Blog_page'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_user_viewed', blank=False,
                             verbose_name=_('User'))

    class Meta:
        verbose_name = _('Blog Viewed')
        verbose_name_plural = _('Blog Vieweds')

    def __str__(self):
        return '[' + self.blog_page.title + '] - ' + self.user.username

pages/blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from pages.blog.models import Blog
from pages.animal.models import Animal

class BlogForm(forms.ModelForm):	
	article = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 100}))

	def __init__(self, *args, **kwargs):
		try:
			user=self.user
			self.img = self.instance.image
			self.fields['article'].required = False
		except:
			pass
		super(BlogForm, self).__init__(*args,**kwargs)
		try:
			if user:
				self.fields['animals'].queryset = Animal.objects.filter(user=user)
		except:
			pass

	class Meta:
		model = Blog
		fields = ['title', 'image', 'article', 'animals']

pages/blog/views.py
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.urls import reverse_lazy, reverse
from blocks.user import AuthFormMixin
from blocks.top_articles import TopArticlesMixin
from blocks.footer import FooterMixin
from django.contrib.auth.models import User
from pages.blog.models import Blog, BlogViewed
from pages.blog.forms import BlogForm
from django.core import serializers
import simplejson as json
from django.shortcuts import render
from blocks.banner import BannerMixin
from django.db.models import Q 
import datetime

def getBlogsView(request,blog_user=None):
    offset = int(request.POST.get('offset') or 0)
    search = request.POST.get('search')
    if blog_user:
        if search:
            articles = Blog.objects.filter(user__username=blog_user).filter( Q(article__contains=search) | Q(title__contains=search) )
        else:
            articles = Blog.objects.filter(user__username=blog_user)
        act_articles = Blog.get_actual_articles(articles=articles)
    else:
        if search:
            articles = Blog.objects.filter( Q(article__contains=search) | Q(title__contains=search) )
        else:
            articles = Blog.objects.all()
        act_articles = Blog.get_actual_articles(articles=articles)
    #return HttpResponse(json.dumps(serializers.serialize('json', act_articles[offset:offset+10])), content_type="application/json")
    return render(request, 'blog_list_ajax.html', {'blog_list':act_articles[offset:offset+3] })


class BlogListAllView(FooterMixin, BannerMixin, TopArticlesMixin, AuthFormMixin, ListView):
    """
    Все блоги
    """
    template_name = 'blog_list.html'
    context_object_name = 'blog_list'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.search = request.GET.get('search')
        return super(BlogListAllView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BlogListAllView, self).get_context_data(**kwargs)
        context['blog_list'] = self.get_queryset()[:3]
        context['settitle'] = 'Список блогов '
        return context

    def get_queryset(self):
        search = self.search
        if search:
            articles = Blog.objects.filter( Q(article__contains=search) | Q(title__contains=search) )
        else:
            articles = Blog.objects.all()
        act_articles = Blog.get_actual_articles(articles=articles)
        return act_articles


class BlogListView(FooterMixin, BannerMixin, TopArticlesMixin, AuthFormMixin, ListView):
    """
    Блог пользователя
    """
    template_name = 'blog_list.html'
    context_object_name = 'blog_list'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.search = request.GET.get('search')
        people = get_object_or_404(User, username=kwargs.get('username'))
        if people.is_active:
            return super(BlogListView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        people = get_object_or_404(User, username=self.kwargs.get('username'))
        context['people'] = people
        context['blog_list'] = self.get_queryset()[:3]
        context['settitle'] = 'Список блогов пользователя ' + people.username
        return context

    def get_queryset(self):
        people = get_object_or_404(User, username=self.kwargs.get('username'))
        search = self.search
        if search:
            articles = Blog.objects.filter(user=people).filter( Q(article__contains=search) | Q(title__contains=search) )
        else:
            articles = Blog.objects.filter(user=people)
        act_articles = Blog.get_actual_articles(articles=articles)
        return act_articles


class BlogDetailView(FooterMixin, BannerMixin, TemplateView, AuthFormMixin):
    """
    Статья
    """
    model = Blog
    template_name = 'blog_detail.html'

    def get_people(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))
        
    def get(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, pk=kwargs.get('pk'))
        author = blog.user
        #views
        user = request.user
        if user.is_authenticated and not self.kwargs.get('username'):
            people = get_object_or_404(User, username=user)
        #else:
        #    people = self.get_people()
        if user.is_authenticated and people != author:
            b_view = BlogViewed.objects.filter(blog_page=blog, user=user)
            if not b_view:
                blog.viewed += 1
                blog.save()
                b_vi = BlogViewed(blog_page=blog, user=user)
                b_vi.save()
        #
        if author.is_active:
            return super(BlogDetailView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        this_object = get_object_or_404(Blog, pk=kwargs.get('pk'))
        context['object'] = this_object
        context['blog_animals'] = this_object.animals.all()
        context['settitle'] = 'Запись в блоге ' + this_object.title

        return context



class BlogCreateView(FooterMixin,CreateView):
    """
    Создание статьи
    """
    template_name = 'blog_create.html'
    model = Blog
    form_class = BlogForm

    def get(self, request, *args, **kwargs):
        user = request.user
        if user and user.is_active:
            self.form_class = BlogForm
            self.form_class.user = user
            return super(BlogCreateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.date = datetime.datetime.now()
        obj.save()
        print(obj)
        return super(BlogCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.object.id})
    

"""
class BlogCreateView(FooterMixin,CreateView):

    template_name = 'blog_create.html'
    model = Blog
    form_class = BlogForm

    def get(self, request, *args, **kwargs):
        user = request.user
        if user and user.is_active:
            self.form = BlogForm(user=user)
            return super(BlogCreateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(BlogCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.object.id})
"""

class BlogUpdateView(FooterMixin,UpdateView):
    """
    Редактирование статьи
    """
    template_name = 'blog_update.html'
    model = Blog
    form_class = BlogForm

    def get(self, request, *args, **kwargs):
        user = request.user
        self.obj = get_object_or_404(Blog, pk=self.kwargs["pk"])
        if (self.obj.user == request.user) and self.obj.user.is_active:
            self.form_class = BlogForm
            self.form_class.instance = self.obj
            self.form_class.user = user
            return super(BlogUpdateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super(BlogUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.object.id})

"""
class BlogUpdateView(FooterMixin,UpdateView):

    template_name = 'blog_update.html'
    model = Blog
    form_class = BlogForm

    def get(self, request, *args, **kwargs):
        user = request.user
        self.obj = get_object_or_404(Blog, pk=self.kwargs["pk"])
        if (self.obj.user == request.user) and self.obj.user.is_active:
            self.form = BlogForm(user=user,instance=self.obj)
            return super(BlogUpdateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def get_success_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.object.id})
"""


class BlogDeleteView(FooterMixin,DeleteView):
    """
    Удаление статьи
    """
    template_name = 'blog_delete.html'
    model = Blog

    def get(self, request, *args, **kwargs):
        self.obj = get_object_or_404(Blog, pk=self.kwargs["pk"])
        if (self.obj.user == request.user) and self.obj.user.is_active:
            return super(BlogDeleteView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('home'))

    def get_context_data(self, **kwargs):
        context = super(BlogDeleteView, self).get_context_data(**kwargs)
        context['obj'] = self.obj
        return context

    def get_success_url(self):
        return reverse_lazy('blog_list', kwargs={'username': self.request.user})

pages/blog/templates/blog_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
	<section class="section-add-article">
	    <div class="block z-depth-1">
			<div class="row">
				<form id="login_form" method="post" action="{% url 'blog_create' %}" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="col s12">
						<label for="id_image">Обложка статьи:</label>
                        <input type="file" id="id_image" name="image" class="dropify" />
					</div>
					<div class="col s12">
						<label for="id_title" class="active">Заголовок:</label>
						{{ form.title|add_class:"input custom-input-filter" }}
					</div>
					<div class="col s12">
						<label for="id_animals" class="active">Упоминаются животные:</label>
						{{ form.animals|add_class:"multiple-select" }}
					</div>
					<div class="input-field col s12">
						{{ form.article|add_class:"materialize-textarea" }}
					</div>
					<div class="col s12 center">
						<button class="btn waves-effect waves-light z-depth-0" type="submit" style="margin-top: 1rem">Добавить статью</button>
						<a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_list' username=user.username %}" style="margin-top: 1rem">Отменить</a>
					</div>
				</form> 
			</div>
	    </div>
	</section>
{% endblock %}

pages/blog/templates/blog_delete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<section class="section-article-delete">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Удаление статьи</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
					<p>Вы уверены что хотите удалить статью "{{ obj.title }}"?</p>
				    <form method="post">
				        {% csrf_token %}
				        <div class="col s12 center">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_detail' pk=object.pk %}" style="margin-top: 1rem">Отменить</a>
				        	<input class="btn red-color waves-effect waves-light z-depth-0" type="submit" value="Удалить">
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

pages/blog/templates/blog_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <section class="section-article">
        <div class="custom-block-header z-depth-1">
            <div class="row margin-bottom-0">
                <nav>
                    <div class="nav-wrapper">
                        <div class="col s12">
                            <a href="/profile/user/{{ object.user.username }}" class="breadcrumb">Профиль пользователя</a>
                            <a href="/blog/list/{{ object.user.username }}" class="breadcrumb">Блог</a>
                            <a href="#" class="breadcrumb">Статья</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="custom-block-body z-depth-1">
            <div class="row">
                <div class="col">
                    <a href="{% url 'user' username=object.user.username %}">
                        {% if object.user.profile.avatar_thumb %}
                            <img src="{{ object.user.profile.avatar_thumb.url }}" class="user-photo responsive-img circle" alt="">
                        {% else %}
                            <img src="{% static '/img/ava_4.png' %}" class="user-photo responsive-img circle" alt="none-avatar">
                        {% endif %}
                    </a>
                </div>
                <div class="col">
                    <h5><a href="{% url 'user' username=object.user.username %}">{{ object.user.first_name }} ({{ object.user.username }}) {{ object.user.last_name }}</a></h5>
                    <p>{{ object.date|date:"d.m.Y H:i" }}</p>
                </div>

                <div class="article col s12">
                    <h5>{{ object.title }}</h5>
                    {% if blog_animals %}
                        <span class="title-animal-chips">Здесь упоминаются:</span>
                        {% for animal in blog_animals %}
                        	<a href="{% url 'animal' pk=animal.pk %}" class="truncate animal-chips">{{ animal.first_name }}</a>
                   		{% endfor %}
                    {% endif %}
                    <p>{{ object.article|safe }}</p>
                </div>
                {% if user.is_authenticated %}
                <div class="write-article col s12 center ">
                    <a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_create' %}" style="margin-top: 1rem;">Написать статью</a>
                    {% if user == object.user %}
                        <a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_update' pk=object.pk %}" style="margin-top: 1rem;">Редактировать</a>
                        <a class="btn red-color waves-effect waves-light z-depth-0" href="{% url 'blog_delete' pk=object.pk %}" style="margin-top: 1rem;">Удалить</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </section>

    <section class="section-comments">
        <div class="block z-depth-1">
            <div class="row">
                <div id="disqus_thread"></div>
                    <script>

                    /**
                    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                    /*
                    var disqus_config = function () {
                    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };
                    */
                    (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://http-185-93-109-126.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                    })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                
            </div>
        </div>
    </section>

{% endblock %}

pages/blog/templates/blog_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <section class="section-search-blog">
      <div class="custom-block z-depth-1">
        <div class="row margin-bottom-0">
          <div class="col s12">
            <div class="row">
              <div class="input-field col s12 m10">
                <input id="autocomplete-input" class="autocomplete custom-input" placeholder="Поиск статей" type="text">
              </div>
              <div class="col s12 m2">
                <button class="btn waves-effect waves-light z-depth-0 col s12" type="submit" name="action">Поиск</button>
              </div> 
            </div>
          </div>
        </div>
      </div>
    </section>
    {% include 'include/top_articles.html' %}

    {% if user.is_authenticated %}
		<div class="write-article center">
      <a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_create' %}">Написать статью</a>
    </div>
    {% endif %}
    
    <section class="section-found-article">
    {% for article in blog_list %}
        <div class="custom-block-header z-depth-1">
          <div class="row margin-bottom-0">
            <div class="col s12">
              <h5><a href="{% url 'blog_detail' pk=article.pk %}">{{ article.title }}</a></h5>
            </div>
          </div>
        </div>
        <div class="custom-block-body z-depth-1">
          <div class="row">
            <div class="col s12 m2 user-post">
              <a href="{% url 'user' username=article.user.profile %}"><img src="{{ article.user.profile.avatar_thumb.url }}" alt="" class="user-photo responsive-img circle"></a>
              <span>{{ article.user.first_name }} {{ article.user.last_name }}</span>
              <p>{{ article.date|date:"d.m.Y H:i" }}</p>
            </div>
            <div class="col s12 m10 article">
              <p>{{ article.article|safe|truncatechars_html:400 }}</p>
              <div class="col s12 center">
                <a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_detail' pk=article.pk %}">Читать</a>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
    <div class="more-article col s12 center">
        <button class="btn waves-effect waves-light blog-moar" value="{{people}}">Показать еще<i class="material-icons right">cached</i></button>
    </div>
    </section>
	
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>
{% endblock %}



pages/blog/templates/blog_list_ajax.html
    {% for article in blog_list %}
        <div class="custom-block-header z-depth-1">
          <div class="row margin-bottom-0">
            <div class="col s12">
              <h5><a href="{% url 'blog_detail' pk=article.pk %}">{{ article.title }}</a></h5>
            </div>
          </div>
        </div>
        <div class="custom-block-body z-depth-1">
          <div class="row">
            <div class="col s12 m2 user-post">
              <a href="{% url 'user' username=article.user.profile %}"><img src="{{ article.user.profile.avatar_thumb.url }}" alt="" class="user-photo responsive-img circle"></a>
              <span>{{ article.user.first_name }} {{ article.user.last_name }}</span>
              <p>{{ article.date|date:"d.m.Y H:i" }}</p>
            </div>
            <div class="col s12 m10 article">
              <p>{{ article.article|safe|truncatechars_html:400 }}</p>
              <div class="col s12 center">
                <a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_detail' pk=article.pk %}">Читать</a>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}

pages/blog/templates/blog_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
	<section class="section-add-article">
	    <div class="block z-depth-1">
			<div class="row">
				<form id="login_form" method="post" action="{% url 'blog_update' pk=object.pk %}" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="col s12">
						<label for="id_image">Обложка статьи:</label>
                        <input type="file" id="id_image" name="image" class="dropify" data-default-file="/media/{{ form.img }}" value="{{ form.img }}" />
					</div>
					<div class="col s12">
						<label for="id_title" class="active">Заголовок:</label>
						{{ form.title|add_class:"input custom-input-filter" }}
					</div>
					<div class="col s12">
						<label for="id_animals" class="active">Упоминаются животные:</label>
						{{ form.animals|add_class:"multiple-select" }}
					</div>
					<div class="input-field col s12">
						{{ form.article|add_class:"materialize-textarea" }}
					</div>
					<div class="col s12 center">
						<button class="btn waves-effect waves-light z-depth-0" type="submit" style="margin-top: 1rem">Сохранить изменения</button>
						<a class="btn waves-effect waves-light z-depth-0" href="{% url 'blog_detail' pk=object.pk %}" style="margin-top: 1rem">Отменить</a>
					</div>
				</form>
			</div>
	    </div>
	</section>
{% endblock %}