chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from chat.views import index
from django.urls import path

urlpatterns = [
    path('', index),
    url(r'^(?P<open_chat>\w+)/?$', index),
]

faunamira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from faunamira import settings
from django.contrib.auth import views as auth_views
from blocks import user

urlpatterns = [
    # админка
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),

    # авторизация
    url(r'^accounts/', include('allauth.urls')),

    # редактор текста
    url(r'^tinymce/', include('tinymce.urls')),

    # страницы
    url(r'^', include('pages.home.urls')),
    url(r'^profile/', include('pages.userprofile.urls')),
    url(r'^animal/', include('pages.animal.urls')),
    url(r'^blog/', include('pages.blog.urls')),
    url(r'^dialogs/', include('pages.messager.urls')),

    # блоки
    url(r'^user_login/$', user.user_login, name='user_login'),
    url(r'^user_signup/$', user.user_signup, name='user_signup'),

    #chat
    url(r'^chat/', include('chat.urls')),

    #password reset
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/animal/models.py
from django.db import models
from dry_library.backend.thumbnails import CreateThumbnail
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User


class KindAnimal(CreateThumbnail, models.Model):
    """
    Справочник видов животных
    """
    kind = models.CharField(max_length=250, blank=False, null=False, verbose_name=_('Kind animal (dog, cat...)'))

    class Meta:
        verbose_name = _('Kind animal')
        verbose_name_plural = _('Kinds animals')

    def __str__(self):
        return self.kind


class KindAnimalAttr(models.Model):
    """
    Справочник характеристик видов животных
    """
    kind = models.ForeignKey(KindAnimal, on_delete=models.CASCADE, related_name='attrs', verbose_name=_('Kind animal'))
    attr = models.CharField(max_length=100, blank=False, null=False, verbose_name=_('Name attr(weight, color...)'))

    class Meta:
        verbose_name = _('Kind attribute')
        verbose_name_plural = _('Kind attributes')

    def __str__(self):
       return self.kind.kind + ' - ' + self.attr
    #def __str__(self):
    #    return self.attr#self.kind.kind + self.attr


class KindAnimalAttrVal(models.Model):
    """
    Справочник значений характеристик видов животных
    """
    attr = models.ForeignKey(KindAnimalAttr, on_delete=models.CASCADE, related_name='attrvals', verbose_name=_('Kind animal attr'))
    value = models.CharField(max_length=100, blank=False, null=False, verbose_name=_('attr val(blue, 40kg...)'))

    class Meta:
        verbose_name = _('Kind attribute value')
        verbose_name_plural = _('Kind attribute values')

    def __str__(self):
        return self.value#self.attr.kind.kind + self.attr.attr + self.value


class Animal(CreateThumbnail, models.Model):
    """
    Модель животного
    """
    user = models.ForeignKey(User, related_name='animals', on_delete=models.CASCADE, verbose_name=_('Owner'))
    first_name = models.CharField(max_length=50, blank=False, null=False, verbose_name=_('Имя'))
    second_name = models.CharField(max_length=50, blank=True, null=True, verbose_name=_('Кличка'))
    GENDER_CHOICES = (
        ('B', _('Мальчик')),
        ('G', _('Девочка')),
    )
    STATUS_CHOICES = (
        ('H', _('В поиске хозяина')),
        ('P', _('В поиске пары')),
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=True, null=True, verbose_name=_('Статус'))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=False, null=True, verbose_name=_('Пол'))
    info = models.TextField(blank=True, null=True, verbose_name=_('О животном'))
    birthday = models.DateField(blank=True, null=True, verbose_name=_('Дата рождения'))
    kind = models.ForeignKey(KindAnimal, related_name='animals', verbose_name=_('Вид'),on_delete=models.CASCADE)
    avatar = models.ImageField(max_length=100, upload_to='animal/avatar', blank=True, null=True,
                               verbose_name=_('Аватар'))
    avatar_thumb = models.ImageField(max_length=100, upload_to='animal/avatar/thumbnail', blank=True, null=True)
    viewed = models.PositiveIntegerField(default=0, verbose_name=_('Viewed'))

    class Meta:
        verbose_name = _('Animal')
        verbose_name_plural = _('Animals')

    def __str__(self):
        return self.first_name

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = Animal.objects.get(pk=self.pk)
            if this_record.avatar != self.avatar:
                this_record.avatar.delete(save=False)
                this_record.avatar_thumb.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=300, height=300, from_img=self.avatar, to_img=self.avatar_thumb)

        force_update = False

        if self.id:
            force_update = True

        super(Animal, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.avatar.delete(save=False)
        self.avatar_thumb.delete(save=False)
        super(Animal, self).delete(*args, **kwargs)


class AnimalAttr(models.Model):
    """
    Характеристики животного
    """
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='AnimalAttr', verbose_name=_('Animal'))
    kind = models.ForeignKey(KindAnimal, related_name='kinds', verbose_name=_('Kind animal'),on_delete=models.DO_NOTHING)
    attr = models.ForeignKey(KindAnimalAttr, related_name='attribues', verbose_name=_('Attributes'),on_delete=models.DO_NOTHING)
    value = models.ForeignKey(KindAnimalAttrVal, related_name='values', verbose_name=_('Attr animal value'),on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Animal attribute')
        verbose_name_plural = _('Animal attributes')

    def __str__(self):
        return self.animal.first_name + self.attr.attr + self.value.value



class AnimalPhoto(CreateThumbnail, models.Model):
    """
    Модель фото животного
    """
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='AnimalPhoto', verbose_name=_('Animal'))
    title = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(max_length=100, upload_to='animal/photo', blank=False, null=False,
                               verbose_name=_('Фотография'))
    photo_thumb = models.ImageField(max_length=100, upload_to='animal/photo/thumbnail', blank=True, null=True)

    class Meta:
        verbose_name = _('AnimalPhoto')
        verbose_name_plural = _('AnimalPhotos')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        self.create_thumbnail(width=300, height=300, from_img=self.photo, to_img=self.photo_thumb)
        super(AnimalPhoto, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.photo.delete(save=False)
        self.photo_thumb.delete(save=False)
        super(AnimalPhoto, self).delete(*args, **kwargs)



class AnimalViewed(models.Model):
    """
    Модель для учета уникальных просмотров животного
    """
    profile_page = models.ForeignKey(User, on_delete=models.CASCADE, related_name='an_user_viewed', blank=False,
                                     verbose_name=_('Profile_page'))
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='animal_viewed', blank=False,
                             verbose_name=_('Animal'))

    class Meta:
        verbose_name = _('Animal Viewed')
        verbose_name_plural = _('Animals Viewed')

    def __str__(self):
        return '[' + self.profile_page.username + '] - ' + self.animal.first_name

refdata/models.py
from django.db import models
from dry_library.backend.thumbnails import CreateThumbnail
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify

from tinymce import models as tinymce_model


class Banner(models.Model):
    """
    Модель для баннера
    """
    title = models.CharField(max_length=30, blank=False, verbose_name=_('Banner name'))
    # content = tinymce_model.HTMLField(blank=True, verbose_name=_('Banner content'))
    image = models.ImageField(max_length=100, upload_to='banner', blank=True, null=True,
                               verbose_name=_('Banner'))
    status = models.BooleanField(default=False, verbose_name=_('Active status'))

    class Meta:
        verbose_name = _('Banner')
        verbose_name_plural = _('Banners')

    def __str__(self):
        return self.title


class AltMenu(models.Model):
    """
    Модель для альтернативного меню
    """
    title = models.CharField(max_length=30, blank=False, verbose_name=_('Title'))
    url = models.URLField(max_length=50, blank=False, verbose_name=_('Url'))
    order = models.PositiveIntegerField(blank=False, verbose_name=_('order'))
    slug = models.SlugField(max_length=30, blank=True, null=True, verbose_name=_('Slug'))

    class Meta:
        verbose_name = _('Additional menu')
        verbose_name_plural = _('Additional menu')
        ordering = ['order']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Создание slug из title
        """
        self.slug = slugify(self.title)
        super(AltMenu, self).save(*args, **kwargs)


class SocialLink(models.Model):
    """
    Ссылки на социальные сети
    """
    TYPES = (                           # Варианты социальных сетей
        ('vk', _('Vkontakte')),
        ('ok', _('Odnoklassniki')),
        ('fb', _('Facebook')),
        ('in', _('Instagram')),
    )
    title = models.CharField(max_length=2, choices=TYPES, blank=False, verbose_name=_('Title'))
    url = models.URLField(max_length=50, blank=False, verbose_name=_('Url'))

    class Meta:
        verbose_name = _('Social links')
        verbose_name_plural = _('Social links')

    def __str__(self):
        return self.title


class Country(models.Model):
    """
    Справочник стран
    """    
    name_ru = models.CharField(max_length=100, verbose_name=_('Name ru'))
    name_en = models.CharField(max_length=100, verbose_name=_('Name en'))
    code = models.CharField(max_length=2, verbose_name=_('Code'))

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countrys')

    def __str__(self):
        return self.name_ru


class City(models.Model):
    """
    Справочник городов
    """
    country_id = models.ForeignKey(Country, on_delete=models.CASCADE, blank=False, null=False, verbose_name=_('Country'))
    name_ru = models.CharField(max_length=100, verbose_name=_('Name ru'))
    name_en = models.CharField(max_length=100, verbose_name=_('Name en'))
    region = models.CharField(max_length=2, verbose_name=_('Region'))
    postal_code = models.CharField(max_length=10, verbose_name=_('Postal code'))
    latitude = models.FloatField(max_length=10.6, null=True, verbose_name=_('Latitude'))
    longitude = models.FloatField(max_length=10.6, null=True, verbose_name=_('Longitude'))
    population = models.IntegerField(null=True, default=0, verbose_name=_('Population'))
    ontop = models.IntegerField(null=True, default=0, verbose_name=_('On top'))

    class Meta:
        verbose_name = _('City')
        verbose_name_plural = _('Cities')

    def __str__(self):
        return self.name_ru



class FilterLogo(CreateThumbnail, models.Model):
    title = models.CharField(max_length=30, blank=False, verbose_name=_('Название'))
    srcimage = models.ImageField(max_length=100, upload_to='logo', blank=True, null=True,
                               verbose_name=_('Исходное изображение'))
    image = models.ImageField(max_length=100, upload_to='logo/thumbnail', blank=True, null=True,
                               verbose_name=_('Изображение'))
    status = models.BooleanField(default=False, verbose_name=_('Активность'))

    class Meta:
        verbose_name = _('Логотип фильтра')
        verbose_name_plural = _('Логотипы фильтра')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = FilterLogo.objects.get(pk=self.pk)
            if this_record.srcimage != self.srcimage:
                this_record.srcimage.delete(save=False)
                this_record.image.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=910, height=410, from_img=self.srcimage, to_img=self.image)
        super(FilterLogo, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.srcimage.delete(save=False)
        self.image.delete(save=False)
        super(FilterLogo, self).delete(*args, **kwargs)

templates/include/banner.html
{% if banner %}
<section class="section-advert">
    <div class="block z-depth-1 center">
        <img src="{{ banner.url }}">
    </div>
</section>
{% endif %}

templates/include/filters.html
{% load staticfiles %}
<section class="section-filter-panel">
    <div class="custom-block-header">
        <div class="row margin-bottom-0">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s4 m2 l2 offset-s1 offset-m2 offset-l3 bold z-depth-1">
                        <a class="active" href="#owner">Владельцы</a>
                    </li>
                    <div class="col m1 l1 hide-on-small-only"></div>
                    <li class="tab col s5 m3 l3 offset-s1 bold z-depth-1">
                        <a href="#pet">Животные</a>
                    </li>
                    <div class="col m2 l1 hide-on-large-only"></div>
                </ul>
            </div>
        </div>
    </div>
    <div class="custom-block-body z-depth-1" {% if filterlogo %} style="background: url( {{ filterlogo.url }} ) no-repeat center; background-size: cover;" {% endif %}>
        <div class="row">
            <div id="owner" class="col s12">
                <form>
                    <!-- <div id="id_gender" class="input-field col s12 xl2">
                        <select>
                            <option value="" disabled selected>Пол</option>
                            <option value="M">Парень</option>
                            <option value="W">Девушка</option>
                        </select>
                    </div> -->
                    <div id="id_wtf" class="input-field col s12 l3 xl4">
                        <select>
                            <option value="" disabled selected>Ищу</option>
                            <option value="M">Парня</option>
                            <option value="W">Девушку</option>
                        </select>
                    </div>
                    <div id="id_age-from" class="input-field col s6 l3 xl2">
                    	<input type="text" maxlength="3" class="custom-input-filter" placeholder="Возраст от">
                    </div>
                    <div id="id_age-before" class="input-field col s6 l3 xl2">
                        <input type="text" maxlength="3" class="custom-input-filter" placeholder="Возраст до">
                    </div>
                    <div id="id_target" class="input-field col s12 l3 xl4">
                        <select>
                            <option value="" disabled selected>Цель знакомства</option>
                            <option value="FNF">Дружба</option>
                            <option value="GOD">Свидание</option>
                            <option value="CMN">Общение</option>           
                        </select>
                    </div>
                    <div class="aut-compl col s12">
                    	<div class="input-field">
                    		<input type="text" id="autocomplete-0" class="autocomplete custom-autocomplete" placeholder="Местоположение">
                    		<div class="results"></div>
                    	</div>
                        <script>
                            var city_data = [];
                            {% for city in cities_list %}
                                city_data.push({"title":"{{ city.name_ru }}", "id":"{{ forloop.counter }}"});
                            {% endfor %}
                        </script>
                    </div>
                    <button id="people_filter_button" class="btn-abs btn waves-effect waves-light z-depth-0" type="submit" name="action">Найти</button>
                </form>
            </div>
            <div id="pet" class="col s12">
                <form>
                    <div id="id_gender" class="input-field col s12 l3 xl2">
                        <select>
                            <option value="" disabled selected>Пол</option>
                            <option value="B">Самец</option>
                            <option value="G">Самка</option>
                        </select>
                    </div>
                    <div id="id_age-from" class="input-field col s6 l3 xl2">
                        <input type="text" maxlength="2" class="custom-input-filter" placeholder="Возраст от">
                    </div>
                    <div id="id_age-before" class="input-field col s6 l3 xl2">
                        <input type="text" maxlength="2" class="custom-input-filter" placeholder="Возраст до">
                    </div>
                    <div id="id_status" class="input-field col s12 l3">
                        <select>
                            <option value="" disabled selected>Статус</option>
                            <option value="H">Ищет хозяина</option>
                            <option value="P">Ищет пару</option>
                        </select>
                    </div>
                    <div id="id_kind" class="input-field col s12 l4 xl3">
                        <select>
                            <option value="" disabled selected>Вид</option>
                            <!-- js populate -->
                        </select>
                    </div>
                    <div class="aut-compl col s12 l8 xl6">
                        <div class="input-field">
                            <input type="text" id="autocomplete-1" class="autocomplete custom-autocomplete" placeholder="Порода" disabled="">
                            <div class="results"></div>
                        </div>
                    </div>
                    <div class="aut-compl col s12 xl6">
                        <div class="input-field" style="z-index:1;">
                            <input type="text" id="autocomplete-2" class="autocomplete custom-autocomplete" placeholder="Местоположение">
                            <div class="results"></div>
                        </div>
                    </div>
                    <button id="animal_filter_button" class="btn-abs btn waves-effect waves-light z-depth-0" type="submit" name="action">Найти</button>
                </form>
            </div>
        </div>
    </div>
</section>

templates/include/footer.html
{% load staticfiles %}

<footer>
    <div class="container">
        <div class="row">
            <div class="block">
                <!-- User main panel footer -->
                <div class="main-footer col s12 m3 l3 xl2">
                    <div class="logo">
                        <a href="/">
                            <img src="{% static 'img/logo.png' %}" class="responsive-img" alt="" width="100">
                        </a>
                    </div>
                    <div class="col s12 padding-0">
                        <ul>
                            {% comment %} <li>
                                <a href="#login">Авторизоваться</a>
                            </li>
                            <li>
                                <a href="#registration">Зарегистрироваться</a>
                            </li>
                            <li>
                                <a href="#">Восстановить пароль</a>
                            </li> {% endcomment %}
                            {% if user.is_authenticated %} {% if user.profile.avatar %}
                            <li class="user-photo padding-0">
                                <a href="{% url 'user' username=user.username %}"><img src="{{ user.profile.avatar_thumb.url }}" class="responsive-img circle"></a> {% endif %}
                            </li>
                            <li class="col s12 padding-0">
                                <a href="{% url 'user' username=user.username %}">{{ user.first_name }} {{ user.last_name }}</a>
                            </li>
                            <li class="col s12 padding-0">
                                <a href="{% url 'account_logout' %}">
                                    {% csrf_token %}
                                    Выйти
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a href="#block_user">Авторизоваться</a>
                            </li>
                            <li>
                                <a href="#block_user">Зарегистрироваться</a>
                            </li>
                            <li>
                                <a href="/password_reset">Восстановить пароль</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <!-- // User main panel footer -->
                <!-- Menu link -->
                <div class="menu-link col s12 m5 l5 xl7">
                    <h5>О проекте</h5>
                    <div class="col s12 padding-0">
                        <ul>
                            {% for fpoint in alt_menu %}
                            <li>
                                <a href="{{ fpoint.url }}">{{ fpoint.title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- // Menu link -->
                <!-- Query popular -->
                <!-- <div class="query-popular col s12 m6 l6 xl4">
                    <h5>Популярные запросы</h5>
                    <div class="query-popular-1 col s6 padding-0">
                        <ul>
                            <li>
                                <a href="#">Первая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Вторая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Третья ссылка</a>
                            </li>
                            <li>
                                <a href="#">Четвертая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Пятая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Шестая ссылка</a>
                            </li>
                        </ul>
                    </div>
                    <div class="query-popular-2 col s6 padding-0">
                        <ul>
                            <li>
                                <a href="#">Первая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Вторая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Третья ссылка</a>
                            </li>
                            <li>
                                <a href="#">Четвертая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Пятая ссылка</a>
                            </li>
                            <li>
                                <a href="#">Шестая ссылка</a>
                            </li>
                        </ul>
                    </div>
                </div> -->
                <!-- // Query popular -->
                <!-- Social link -->
                <div class="social-link-footer col s12 m4 l4 xl3">
                    <h5>Социальные сети</h5>
                    <div class="col s12 padding-0">
                        <a href="{{ link_vk.url }}"><img src="{% static 'img/soc/vk.png' %}" alt="" class="responsive-img soc-icon"></a>
                        <!-- <a href="{{ link_fb.url }}"><img src="{% static 'img/soc/fb.png' %}" alt="" class="responsive-img soc-icon"></a> -->
                        <a href="{{ link_ok.url }}"><img src="{% static 'img/soc/odnoklassniki.png' %}" alt="" class="responsive-img soc-icon"></a>
                        <!--  <img src="img/gplus.png" alt="" class="responsive-img soc-icon"> -->
                        <!-- <a href="{{ link_in.url }}"><img src="{% static 'img/soc/mailru.png' %}" alt="" class="responsive-img soc-icon"></a> -->
                        <!--  <img src="img/ya.png" alt="" class="responsive-img soc-icon"> -->
                    </div>
                </div>
                <!-- // Social link -->
            </div>
        </div>
        <div class="row" class="margin-0 padding-0">
            <!-- About -->
            <div class="about col s12">
                <span>Фауна Мира &ndash; первый социальный сайт для знакомства владельцев животных.</span>
            </div>
            <!-- // About -->
            <!-- Copyright -->
            <div class="copyright col s12">
                <span>&copy; 2018 Все права защищены.</span>
            </div>
            <!-- // Copyright -->
        </div>
    </div>
</footer>

templates/include/latest_articles.html
{% load staticfiles %}

<section class="section-last-article">
    <div class="custom-block-header z-depth-1">
        <div class="row margin-bottom-0">
            <div class="col s12 header-block clearfix padding-0">
                <div class="col s9 m10">
                    <h5><a href="/blog/">Последние записи в блогах</a></h5>
                </div>
                <div class="col right-align navig"></div>
            </div>
        </div>
    </div>
    <div class="custom-block-body">
        <div class="row margin-bottom-0">

            {% for lart in latest_articles %}
                <div class="crsl-item z-depth-1">
                    <div class="thumbnail">
                        <a href="{% url 'blog_detail' pk=lart.pk %}">
                            {% if lart.image %}
                                <img src="/media/{{ lart.image_thumb }}" alt="image" class="responsive-img">
                            {% else %}
                                <img src="{% static '/img/ava_4-260x190.png' %}" alt="none-image" class="responsive-img">
                            {% endif %}
                        </a>
                    </div>
                    <h5>
                        <a href="{% url 'blog_detail' pk=lart.pk %}">{{ lart.title|truncatechars:20 }}</a>
                    </h5>
                </div>
            {% endfor %}

        </div>
    </div>
</section>

templates/include/my_animals.html
{% if user_animals %}

    <section class="section-my-pets">
        <div class="custom-block-header pb0 z-depth-1">
            <div class="row margin-bottom-0">
                <div class="col s12 header-block clearfix padding-0">
                    <div class="col s9">
                        <h5>Мои питомцы</h5>
                    </div>
                    <div class="col right-align navig"></div>
                </div>
            </div>
        </div>
        <div class="custom-block-body">
            <div class="row margin-bottom-0">
                {% for animal in user_animals %}
                    <div class="pets col s4 center">
                        <a href="{% url 'animal' pk=animal.pk %}" class="tooltipped" data-position="top" data-delay="10" data-tooltip="{{ animal.first_name }}">
                            {% if animal.avatar_thumb %}<img src="{{ animal.avatar_thumb.url }}" alt="" class="responsive-img circle z-depth-1">
                            {%else%}<img src="/static/img/ava_4.png" alt="" class="responsive-img circle z-depth-1">
                            {%endif%}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endif  %}

templates/include/random_profiles.html
{% load staticfiles  %}

    <!-- {% for ruser in random_users %}
        <div>
            <a href="{% url 'user' username=ruser.username %}">
                {% if ruser.profile.avatar_thumb %}
                    <img src="{{ ruser.profile.avatar_thumb.url }}">
                {% else %}
                    <p>{{ ruser.username }}</p>
                {% endif %}
            </a>
        </div>
    {% endfor %} -->

<noscript>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fallback.css' %}" />
</noscript>
<!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fallback.css' %}" />
<![endif]-->
<!-- {% if not banner.url %} offset-xl4 {% endif %} -->
<section class="section-grid-random">
    <div class="block z-depth-1 padding-0">

        <div id="ri-grid" class="ri-grid ri-grid-size-1">
            <img class="ri-loading-image" src="{% static 'img/loading.gif' %}" />
            <ul>
                <!-- <li>
                    <a href="#">
                        <img src="{% static 'img/restart.jpg' %}" />
                    </a>
                </li> -->
                {% for ruser in random_users %}
                    <li>
                        {% if ruser.profile.avatar and ruser.profile.avatar_thumb %}
                            <a href="{% url 'user' username=ruser.username %}">
                                <img src="{{ ruser.profile.avatar_thumb.url }}" />
                            </a>
                        {% else %}
                            <a href="{% url 'user' username=ruser.username %}">
                                <img src="{% static '/img/ava_4.png' %}" class="responsive-img z-depth-1" alt="none-avatar">
                            </a>                            
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
</section>