chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from chat.views import index
from django.urls import path

urlpatterns = [
    path('', index),
    url(r'^(?P<open_chat>\w+)/?$', index),
]

faunamira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from faunamira import settings
from django.contrib.auth import views as auth_views
from blocks import user

urlpatterns = [
    # админка
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),

    # авторизация
    url(r'^accounts/', include('allauth.urls')),

    # редактор текста
    url(r'^tinymce/', include('tinymce.urls')),

    # страницы
    url(r'^', include('pages.home.urls')),
    url(r'^profile/', include('pages.userprofile.urls')),
    url(r'^animal/', include('pages.animal.urls')),
    url(r'^blog/', include('pages.blog.urls')),
    url(r'^dialogs/', include('pages.messager.urls')),

    # блоки
    url(r'^user_login/$', user.user_login, name='user_login'),
    url(r'^user_signup/$', user.user_signup, name='user_signup'),

    #chat
    url(r'^chat/', include('chat.urls')),

    #password reset
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/userprofile/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from pages.userprofile.views import ProfileView, ProfileUpdateView, ProfileChangePassword, \
    ProfileDelete, ProfileDeleteSuccess, ProfileImageAdd, ProfileImageDelete, ProfileImageUpdate
from pages.userprofile.async import get_about_edit_form, post_about_edit_form, similar_people

urlpatterns = [
    # аккаунт
    url(r'^$', ProfileView.as_view(), name='userMe'),
    url(r'^user/(?P<username>.+)/', ProfileView.as_view(), name='user'),

    # функции для ajax
    url(r'^get_edit_about/$', get_about_edit_form, name='about_edit'),    # редактирование Обо мне
    url(r'^post_edit_about/$', post_about_edit_form, name='about_edit'),
    url(r'^get_similar_people/$', similar_people, name='similar_people'),   # похожие анкеты "Показать еще"

    # редактирование аккаунта
    url(r'^update/(?P<username>.+)/$', ProfileUpdateView.as_view(), name='user_update'),
    url(r'^password/(?P<username>.+)/$', ProfileChangePassword.as_view(), name='user_password'),
    url(r'^delete/(?P<username>.+)/$', ProfileDelete.as_view(), name='user_delete'),
    url(r'^delete_success/(?P<username>.+)/$', ProfileDeleteSuccess.as_view(), name='user_delete_success'),

    # фото пользователя
    url(r'addphoto/$', ProfileImageAdd.as_view(), name='user_image_add'),
    url(r'updphoto/(?P<pk>[0-9]+)/$', ProfileImageUpdate.as_view(), name='user_image_upd'),
    url(r'delphoto/(?P<pk>[0-9]+)/$', ProfileImageDelete.as_view(), name='user_image_del'),
]

pages/userprofile/models.py
from django.db import models

# сигналы
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.contrib.auth.models import User
from refdata.models import City
from dry_library.backend.thumbnails import CreateThumbnail

from django.utils.translation import ugettext_lazy as _


class ProfileHobby(models.Model):
    """
    Интересы пользователя
    """
    name = models.CharField(max_length=50, blank=False, verbose_name=_('Hobby name'))

    class Meta:
        verbose_name = _('Hobby')
        verbose_name_plural = _('Hobbies')

    def __str__(self):
        return self.name


class Profile(CreateThumbnail, models.Model):
    """
    Модель расширяющая стандартную User
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', verbose_name=_('User'))
    GENDER_CHOICES = (
        ('M', _('Мужчина')),
        ('W', _('Женщина')),
    )    
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True, verbose_name=_('Пол'))
    phone = models.CharField(max_length=30, blank=True, null=True, verbose_name=_('Телефон'))
    info = models.TextField(blank=True, null=True, verbose_name=_('Обо мне'))
    birthday = models.DateField(blank=True, null=True, verbose_name=_('Дата рождения'))
    avatar = models.ImageField(max_length=100, upload_to='profile/avatar', blank=True, null=True,
                               verbose_name=_('Аватар'))
    avatar_thumb = models.ImageField(max_length=100, upload_to='profile/avatar/thumbnail', blank=True, null=True)
    hobbies = models.ManyToManyField(ProfileHobby, blank=True, verbose_name=_('Интересы'))
    viewed = models.PositiveIntegerField(default=0, verbose_name=_('Viewed'))
    last_visit = models.DateTimeField(blank=True, null=True, verbose_name=_('Last date of visit'))
    vk = models.URLField(max_length=100, blank=True, null=True, verbose_name=_('Vkontakte'))
    ok = models.URLField(max_length=100, blank=True, null=True, verbose_name=_('Odnoklassniki'))
    fb = models.URLField(max_length=100, blank=True, null=True, verbose_name=_('Facebook'))
    insta = models.URLField(max_length=100, blank=True, null=True, verbose_name=_('Instagram'))
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_('Город'))

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
            instance.profile.save()

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = Profile.objects.get(pk=self.pk)
            if this_record.avatar != self.avatar:
                this_record.avatar.delete(save=False)
                this_record.avatar_thumb.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=300, height=300, from_img=self.avatar, to_img=self.avatar_thumb)

        force_update = False

        if self.id:
            force_update = True

        super(Profile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.avatar.delete(save=False)
        self.avatar_thumb.delete(save=False)
        super(Profile, self).delete(*args, **kwargs)


class ProfileImages(CreateThumbnail, models.Model):
    """
    Изображения пользователя
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images', verbose_name=_('User'))
    image = models.ImageField(max_length=100, upload_to='profile/images', blank=False, null=False,
                              verbose_name=_('Photo'))
    image_thumb = models.ImageField(max_length=100, upload_to='profile/images/thumbnail', blank=False, null=False,)
    date = models.DateTimeField(auto_now_add=True, blank=False, null=False, verbose_name=_('Date added'))
    description = models.CharField(max_length=250, blank=True, null=True, verbose_name=_('Description'))

    class Meta:
        ordering = ['-date']
        verbose_name = _('Profile image')
        verbose_name_plural = _('Profile images ')

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = ProfileImages.objects.get(pk=self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
                this_record.image_thumb.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=300, height=300, from_img=self.image, to_img=self.image_thumb)

        force_update = False

        if self.id:
            force_update = True
        super(ProfileImages, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.image.delete(save=False)
        self.image_thumb.delete(save=False)
        super(ProfileImages, self).delete(*args, **kwargs)


class ProfileAbout(models.Model):
    """
    Информация о пользователе
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='about', blank=False, verbose_name=_('User'))
    FIND_CHOICES = (
        ('M', _('Мужчина')),
        ('W', _('Женщина')),
    )
    find = models.CharField(max_length=2, choices=FIND_CHOICES, blank=True, verbose_name=_('Я ищу'))
    GOAL_CHOICES = (
        ('CMN', _('Общение')),
        ('FNF', _('Дружба')),
        ('GOD', _('Свидание')),
    )
    purpose = models.CharField(max_length=3, choices=GOAL_CHOICES, blank=True, verbose_name=_('Цель знакомства'))
    about_me = models.TextField(blank=True, verbose_name=_('Обо мне'))

    class Meta:
        verbose_name = _('Profile About')
        verbose_name_plural = _('Profiles About')



class ProfileViewed(models.Model):
    """
    Модель для учета уникальных просмотров профиля пользователя
    """
    profile_page = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_viewed', blank=False,
                                     verbose_name=_('Profile_page'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile_viewed', blank=False,
                             verbose_name=_('User'))

    class Meta:
        verbose_name = _('Profile Viewed')
        verbose_name_plural = _('Profiles Vieweds')

    def __str__(self):
        return '[' + self.profile_page.username + '] - ' + self.user.username

pages/userprofile/forms.py
from django.forms import ModelForm
from allauth.account.forms import ChangePasswordForm
from django.contrib.auth.models import User
from pages.userprofile.models import Profile, ProfileImages, ProfileAbout

class ProfileAboutForm(ModelForm):
    """
    Форма на странице пользователя 'Обо мне'
    """
    class Meta:
        model = ProfileAbout
        fields = ('find', 'purpose', 'about_me')


class UserForm(ModelForm):
    """
    Форма для редактирования основной информации пользователя
    """
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class ProfileForm(ModelForm):
    """
    Форма для редактирования дополнительной информации пользователя
    """
    class Meta:
        model = Profile
        fields = ('gender', 'phone', 'info', 'birthday', 'avatar', 'vk', 'ok', 'fb', 'insta')


class PasswordChangeForm(ChangePasswordForm):
    """
    Форма для смены пароля
    """
    class Meta:
        model = User
        fields = ('oldpassword', 'password1', 'password2')


class ProfileImageForm(ModelForm):
    """
    Форма загрузки фотографии
    """
    class Meta:
        model = ProfileImages
        fields = ('image', 'description')

pages/userprofile/templates/include/edit_profile_about.html
{% if about %}
{% load widget_tweaks %}
    <section class="section-user-about">
        <div class="custom-block-header z-depth-1">
            <div class="row margin-bottom-0">
                <div class="col l12">
                    <h5>Обо мне</h5>
                    {% if request.user == people %}
                        <h5 class="right"><a href="{% url 'user_update' user.username %}#about" id="about-edit"><i class="material-icons">edit</i></a></h5> 
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="custom-block-body z-depth-1">
            <div class="row">
                <div class="col s12">
                    <!-- <h5>Интересы</h5>
                    <a href="search-filter.html">Прогулки с животными</a>,
                    <a href="search-filter.html">Друзья</a>,
                    <a href="search-filter.html">Вечеринки</a>,
                    <a href="search-filter.html">Семья</a> -->
                    <h5>Я ищу:</h5>
                    <span>{{ about.get_find_display }}</span>
                    <h5>Цель знакомства:</h5>
                    <span>{{ about.get_purpose_display }}</span>
                    <h5>Обо мне:</h5>
                    <span>{{ about.about_me }}</span>

                </div>
            </div>
        </div>
    </section>
{# {% elif form and request.user == people %} #}
<!--     <section class="section-user-about">
        <div class="custom-block-header z-depth-1">
            <div class="row margin-bottom-0">
                <div class="col l12">
                    <h5>Обо мне</h5>
                </div>
            </div>
        </div>
        <div class="custom-block-body z-depth-1">
            <div class="row">
                <div class="col s12">
                    <form method="post">
                        {% csrf_token %} 
                        <p>
                            <label for="id_find" class="active">Я ищу:</label> 
                            {{ form.find|add_class:"browser-default" }}
                        </p>
                        <p>
                            <label for="id_purpose" class="active">Цель знакомства:</label> 
                            {{ form.purpose|add_class:"browser-default" }}
                        </p>
                        <p>
                            <label for="id_about_me" class="active">Обо мне:</label> 
                            {{ form.about_me|add_class:"input custom-input-filter" }}
                        </p>
                        <input type="submit" id="about-submit" value="Сохранить">
                    </form>
                </div>
            </div>
        </div>
    </section> -->
{% endif %}

pages/userprofile/templates/include/similar_people.html
{% load staticfiles online %}

<section class="section-similar-profiles">
    <div class="custom-block-header pb0 z-depth-1">
        <div class="row margin-bottom-0">
            <div class="col s12 header-block clearfix padding-0">
                <div class="col s9 m10">
                    <h5>Похожие анкеты</h5>
                </div>
                <div class="col right-align navig">
                </div>
            </div>
        </div>
    </div>
    <div class="custom-block-body z-depth-1">
        <div class="row margin-bottom-0">

            {% for tuser in similar_people %}
            <div class="crsl-item">
                <a href="{% url 'user' username=tuser.username %}">
                    {% if tuser.profile.avatar %}
                    <img src="{{ tuser.profile.avatar_thumb.url }}" class="responsive-img"> 
                    {% else %}
                    <img src="{% static '/img/ava_4.png' %}" class="responsive-img z-depth-1" alt="none-avatar">                     
                    {% endif %}
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
</section>