chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from chat.views import index
from django.urls import path

urlpatterns = [
    path('', index),
    url(r'^(?P<open_chat>\w+)/?$', index),
]

faunamira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from faunamira import settings
from django.contrib.auth import views as auth_views
from blocks import user

urlpatterns = [
    # админка
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),

    # авторизация
    url(r'^accounts/', include('allauth.urls')),

    # редактор текста
    url(r'^tinymce/', include('tinymce.urls')),

    # страницы
    url(r'^', include('pages.home.urls')),
    url(r'^profile/', include('pages.userprofile.urls')),
    url(r'^animal/', include('pages.animal.urls')),
    url(r'^blog/', include('pages.blog.urls')),
    url(r'^dialogs/', include('pages.messager.urls')),

    # блоки
    url(r'^user_login/$', user.user_login, name='user_login'),
    url(r'^user_signup/$', user.user_signup, name='user_signup'),

    #chat
    url(r'^chat/', include('chat.urls')),

    #password reset
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/animal/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from pages.animal.views import AnimalView, AnimalCreateView, AnimalUpdateView, AnimalDeleteView, AttrCreateView, \
    AttrUpdateView, AttrDeleteView, getAnimalsView, PhotoDeleteView, PhotoCreateView

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/', AnimalView.as_view(), name='animal'),
    url(r'^create/$', AnimalCreateView.as_view(), name='animal_create'),
    url(r'^update/(?P<pk>[0-9]+)/', AnimalUpdateView.as_view(), name='animal_update'),
    url(r'^delete/(?P<pk>[0-9]+)/', AnimalDeleteView.as_view(), name='animal_delete'),
    url(r'^addattr/(?P<pk>[0-9]+)/', AttrCreateView.as_view(), name='attr_create'),
    url(r'^updattr/(?P<pk>[0-9]+)/', AttrUpdateView.as_view(), name='attr_update'),
    url(r'^delattr/(?P<pk>[0-9]+)/', AttrDeleteView.as_view(), name='attr_delete'),
    url(r'^addphoto/(?P<pk>[0-9]+)/', PhotoCreateView.as_view(), name='photo_create'),
    url(r'^delphoto/(?P<pk>[0-9]+)/', PhotoDeleteView.as_view(), name='photo_delete'),
    url(r'^getAnimals/?$', getAnimalsView, name='getAnimals'),
    
]

pages/animal/models.py
from django.db import models
from dry_library.backend.thumbnails import CreateThumbnail
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User


class KindAnimal(CreateThumbnail, models.Model):
    """
    Справочник видов животных
    """
    kind = models.CharField(max_length=250, blank=False, null=False, verbose_name=_('Kind animal (dog, cat...)'))

    class Meta:
        verbose_name = _('Kind animal')
        verbose_name_plural = _('Kinds animals')

    def __str__(self):
        return self.kind


class KindAnimalAttr(models.Model):
    """
    Справочник характеристик видов животных
    """
    kind = models.ForeignKey(KindAnimal, on_delete=models.CASCADE, related_name='attrs', verbose_name=_('Kind animal'))
    attr = models.CharField(max_length=100, blank=False, null=False, verbose_name=_('Name attr(weight, color...)'))

    class Meta:
        verbose_name = _('Kind attribute')
        verbose_name_plural = _('Kind attributes')

    def __str__(self):
       return self.kind.kind + ' - ' + self.attr
    #def __str__(self):
    #    return self.attr#self.kind.kind + self.attr


class KindAnimalAttrVal(models.Model):
    """
    Справочник значений характеристик видов животных
    """
    attr = models.ForeignKey(KindAnimalAttr, on_delete=models.CASCADE, related_name='attrvals', verbose_name=_('Kind animal attr'))
    value = models.CharField(max_length=100, blank=False, null=False, verbose_name=_('attr val(blue, 40kg...)'))

    class Meta:
        verbose_name = _('Kind attribute value')
        verbose_name_plural = _('Kind attribute values')

    def __str__(self):
        return self.value#self.attr.kind.kind + self.attr.attr + self.value


class Animal(CreateThumbnail, models.Model):
    """
    Модель животного
    """
    user = models.ForeignKey(User, related_name='animals', on_delete=models.CASCADE, verbose_name=_('Owner'))
    first_name = models.CharField(max_length=50, blank=False, null=False, verbose_name=_('Имя'))
    second_name = models.CharField(max_length=50, blank=True, null=True, verbose_name=_('Кличка'))
    GENDER_CHOICES = (
        ('B', _('Мальчик')),
        ('G', _('Девочка')),
    )
    STATUS_CHOICES = (
        ('H', _('В поиске хозяина')),
        ('P', _('В поиске пары')),
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=True, null=True, verbose_name=_('Статус'))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=False, null=True, verbose_name=_('Пол'))
    info = models.TextField(blank=True, null=True, verbose_name=_('О животном'))
    birthday = models.DateField(blank=True, null=True, verbose_name=_('Дата рождения'))
    kind = models.ForeignKey(KindAnimal, related_name='animals', verbose_name=_('Вид'),on_delete=models.CASCADE)
    avatar = models.ImageField(max_length=100, upload_to='animal/avatar', blank=True, null=True,
                               verbose_name=_('Аватар'))
    avatar_thumb = models.ImageField(max_length=100, upload_to='animal/avatar/thumbnail', blank=True, null=True)
    viewed = models.PositiveIntegerField(default=0, verbose_name=_('Viewed'))

    class Meta:
        verbose_name = _('Animal')
        verbose_name_plural = _('Animals')

    def __str__(self):
        return self.first_name

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        try:
            this_record = Animal.objects.get(pk=self.pk)
            if this_record.avatar != self.avatar:
                this_record.avatar.delete(save=False)
                this_record.avatar_thumb.delete(save=False)
        except:
            pass

        self.create_thumbnail(width=300, height=300, from_img=self.avatar, to_img=self.avatar_thumb)

        force_update = False

        if self.id:
            force_update = True

        super(Animal, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.avatar.delete(save=False)
        self.avatar_thumb.delete(save=False)
        super(Animal, self).delete(*args, **kwargs)


class AnimalAttr(models.Model):
    """
    Характеристики животного
    """
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='AnimalAttr', verbose_name=_('Animal'))
    kind = models.ForeignKey(KindAnimal, related_name='kinds', verbose_name=_('Kind animal'),on_delete=models.DO_NOTHING)
    attr = models.ForeignKey(KindAnimalAttr, related_name='attribues', verbose_name=_('Attributes'),on_delete=models.DO_NOTHING)
    value = models.ForeignKey(KindAnimalAttrVal, related_name='values', verbose_name=_('Attr animal value'),on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Animal attribute')
        verbose_name_plural = _('Animal attributes')

    def __str__(self):
        return self.animal.first_name + self.attr.attr + self.value.value



class AnimalPhoto(CreateThumbnail, models.Model):
    """
    Модель фото животного
    """
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='AnimalPhoto', verbose_name=_('Animal'))
    title = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(max_length=100, upload_to='animal/photo', blank=False, null=False,
                               verbose_name=_('Фотография'))
    photo_thumb = models.ImageField(max_length=100, upload_to='animal/photo/thumbnail', blank=True, null=True)

    class Meta:
        verbose_name = _('AnimalPhoto')
        verbose_name_plural = _('AnimalPhotos')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Сохранение фото
        """
        self.create_thumbnail(width=300, height=300, from_img=self.photo, to_img=self.photo_thumb)
        super(AnimalPhoto, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        Удаление фото
        """
        self.photo.delete(save=False)
        self.photo_thumb.delete(save=False)
        super(AnimalPhoto, self).delete(*args, **kwargs)



class AnimalViewed(models.Model):
    """
    Модель для учета уникальных просмотров животного
    """
    profile_page = models.ForeignKey(User, on_delete=models.CASCADE, related_name='an_user_viewed', blank=False,
                                     verbose_name=_('Profile_page'))
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='animal_viewed', blank=False,
                             verbose_name=_('Animal'))

    class Meta:
        verbose_name = _('Animal Viewed')
        verbose_name_plural = _('Animals Viewed')

    def __str__(self):
        return '[' + self.profile_page.username + '] - ' + self.animal.first_name

pages/animal/forms.py
from django.forms import ModelForm, inlineformset_factory, modelformset_factory


from pages.animal.models import Animal, AnimalAttr, KindAnimalAttr,AnimalPhoto


class AnimalForm(ModelForm):

    class Meta:
        model = Animal
        fields = ['first_name', 'second_name', 'gender', 'info', 'birthday', 'kind', 'avatar']


class AnimalAttrForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(AnimalAttrForm, self).__init__(*args,**kwargs)
        try:
        	attrs_already_have = list(AnimalAttr.objects.filter(animal=self.instance).values('attr').values_list('attr', flat=True))
        	kinds = KindAnimalAttr.objects.filter(kind=self.instance.kind)
        	attrs_filtered = kinds.exclude(id__in=attrs_already_have)
       		self.fields['attr'].queryset = attrs_filtered
       	except:
       		pass

        #super(AnimalAttrForm, self).__init__(*args, **kwargs)


    class Meta:
        model = AnimalAttr
        fields = ['attr', 'value']


class AnimalUpdAttrForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(AnimalUpdAttrForm, self).__init__(*args,**kwargs)
        try:
        	attrs = list(AnimalAttr.objects.filter(pk=self.instance.pk).values('attr').values_list('attr', flat=True))
        	kinds = KindAnimalAttr.objects.filter(id__in=attrs)
       		self.fields['attr'].queryset = kinds
       	except:
       		pass

    class Meta:
        model = AnimalAttr
        fields = ['attr', 'value']



class AnimalPhotoForm(ModelForm):

    class Meta:
        model = AnimalPhoto
        fields = ['title', 'photo']



#AnimalFormset = inlineformset_factory(Animal, AnimalAttr, fields=('attr', 'value'))
#AnimalFormset = modelformset_factory(AnimalAttr, form=AnimalAttrForm, fields=('attr', 'value'))

pages/animal/templates/animal_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}

<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700,900|Roboto+Condensed:400,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	 
	{% include 'include/my_animals.html' %}

	<section class="section-add-animal">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Добавление животного</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
				    <form id="login_form" method="post" enctype='multipart/form-data'>
				        {% csrf_token %}
				        <p>
				        	<label for="id_avatar">Аватар:</label>
				        	<input type="file" id="id_avatar" name="avatar" class="dropify" data-height="300" />
				        </p>
				        <p>
				        	<label for="id_first_name" class="">Имя:</label>
				        	{{ form.first_name|add_class:"input custom-input-filter" }}
				        </p>
				        <p>
				        	<label for="id_gender">Пол:</label> 
							{{ form.gender|add_class:"browser-default" }}
				        </p>
				        <p>
				        	<label for="id_birthday" class="">Дата рождения:</label> 
				        	{{ form.birthday|add_class:"input custom-input-filter datepicker" }}
				        </p>
				        <p>
				        	<label for="id_kind">Вид:</label> 
							{{ form.kind|add_class:"browser-default" }}
				        </p>
				        <p>
				        	<label for="id_info" class="">О животном:</label> 
				        	{{ form.info|add_class:"input custom-input-filter materialize-textarea ta100" }}
				        </p>
				        <div class="col s12 center">
				        	<input class="btn waves-effect waves-light z-depth-0" type="submit" value="Добавить">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'user' username=user.username %}" style="margin-top: 1rem">Отменить</a>
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

pages/animal/templates/animal_delete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	 
	<section class="section-delete-animal">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Удаление животного</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
					<p>Вы уверены, что хотите удалить питомца {{ obj.first_name }}?</p>
				    <form method="post">
				        {% csrf_token %}
				        <div class="col s12 center">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=obj.pk %}" style="margin-top: 1rem">Отменить</a>
				        	<input class="btn red-color waves-effect waves-light z-depth-0" type="submit" value="Удалить">
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

pages/animal/templates/animal_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}

<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700,900|Roboto+Condensed:400,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	 
	<section class="section-update-animal">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Редактирование информации животного</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
				    <form id="login_form" method="post" enctype='multipart/form-data'>
				        {% csrf_token %}
				        <p>
				        	<label for="id_avatar">Аватар:</label>
				        	<input type="file" id="id_avatar" name="avatar" class="dropify" data-default-file="/media/{{ animal.avatar }}" data-height="300" />
				        </p>
				        <p>
				        	<label for="id_first_name" class="">Имя:</label>
				        	{{ form.first_name|add_class:"input custom-input-filter" }}
				        </p>
				        <p>
				        	<label for="id_gender">Пол:</label> 
							{{ form.gender|add_class:"browser-default" }}
				        </p>
				        <p>
				        	<label for="id_birthday" class="">Дата рождения:</label> 
				        	{{ form.birthday|add_class:"input custom-input-filter datepicker" }}
				        </p>
				        <p>
				        	<label for="id_kind">Вид:</label> 
							{{ form.kind|add_class:"browser-default" }}
				        </p>
				        <p>
				        	<label for="id_info" class="">О животном:</label> 
				        	{{ form.info|add_class:"input custom-input-filter materialize-textarea ta100" }}
				        </p>
				        <div class="col s12 center">
				        	<input class="btn waves-effect waves-light z-depth-0" type="submit" value="Редактировать">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

pages/animal/templates/attr_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
    <section class="section-add-attributes">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Добавление характеристик</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
				    <form method="post">
				        {% csrf_token %}
				        <input type="hidden" id="get_kind" value="{{animal.kind}}">
						<p>
							<label for="id_attr">Характеристика:</label>
							{{ form.attr|add_class:"browser-default" }}
						</p>
						<p>
							<label for="id_value">Значение характеристики:</label>
							{{ form.value|add_class:"browser-default"|attr:"disabled:disabled" }}
						</p>
				        <div class="col s12 center">
				        	<input class="btn waves-effect waves-light z-depth-0" type="submit" value="Добавить">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/animal.js' %}"></script>
{% endblock %}

pages/animal/templates/attr_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section class="section-del-attributes">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Удаление характеристики</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
					<p>Вы уверены, что хотите удалить характеристику "{{ obj.attr.attr }}"?</p>
				    <form method="post">
				        {% csrf_token %}
				        <div class="col s12 center">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        	<input class="btn red-color waves-effect waves-light z-depth-0" type="submit" value="Удалить">
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

pages/animal/templates/attr_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
    <section class="section-upd-attributes">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Редактирование характеристики</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
				    <form method="post">
				        {% csrf_token %}
				        <input type="hidden" id="get_kind" value="{{animal.kind}}">
						<p>
							<label for="id_attr">Характеристика:</label>
							{{ form.attr|add_class:"browser-default" }}
						</p>
						<p>
							<label for="id_value">Значение характеристики:</label>
							{{ form.value|add_class:"browser-default"|attr:"disabled:disabled" }}
						</p>
				        <div class="col s12 center">
				        	<input class="btn waves-effect waves-light z-depth-0" type="submit" value="Сохранить">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/animal.js' %}"></script>
{% endblock %}

pages/animal/templates/photo_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}

<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700,900|Roboto+Condensed:400,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <section class="section-add-photo">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Добавление фотографии животного</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
					<form id="login_form" method="post" enctype='multipart/form-data'>
				        {% csrf_token %}
						<p>
							<label for="id_photo">Фотография:</label>
							<input type="file" id="id_photo" name="photo" class="dropify" data-height="300" />
						</p>
						<p>
							<label for="id_title" class="">Заголовок:</label>
							{{ form.title|add_class:"input custom-input-filter" }}
						</p>
						<div class="col s12 center">
				        	<input class="btn waves-effect waves-light z-depth-0" type="submit" value="Добавить">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        </div>
					</form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

pages/animal/templates/photo_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section class="section-del-photo">
		<div class="custom-block-header z-depth-1">
			<div class="row margin-bottom-0">
				<div class="col s12">
					<h5>Удаление фотографии</h5>
				</div>
			</div>
		</div>
		<div class="custom-block-body z-depth-1">
			<div class="row">
				<div class="col s12">
					<img src="{{ obj.photo_thumb.url }}" alt="{{ obj.title }}" class="responsive-img">
					<p>Вы уверены, что хотите удалить эту фотографию?</p>
				    <form method="post">
				        {% csrf_token %}
				        <div class="col s12 center">
				        	<a class="btn waves-effect waves-light z-depth-0" href="{% url 'animal' pk=animal.pk %}" style="margin-top: 1rem">Отменить</a>
				        	<input class="btn red-color waves-effect waves-light z-depth-0" type="submit" value="Удалить">
				        </div>
				    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}